# Generated by Django 3.0.8 on 2021-05-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsBuddyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='competive',
        ),
    ]
