# Generated by Django 3.1.7 on 2021-05-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsBuddyApp', '0003_event_competive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='competive',
            new_name='competitive',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
    ]
