# Generated by Django 3.0.8 on 2021-05-27 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportsBuddyApp', '0005_auto_20210527_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmed_users',
            field=models.ManyToManyField(blank=True, related_name='confirmed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
