# Generated by Django 3.1.3 on 2021-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsBuddyApp', '0007_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='Event Description'),
        ),
    ]
