# Generated by Django 3.1.3 on 2021-07-05 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsBuddyApp', '0009_auto_20210627_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
