# Generated by Django 3.1.7 on 2021-06-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsrequest',
            old_name='from_User',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendsrequest',
            old_name='to_User',
            new_name='to_user',
        ),
    ]
