# Generated by Django 3.1.3 on 2021-06-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210627_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_events',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='joined_events',
        ),
    ]
