# Generated by Django 3.0.8 on 2021-06-13 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportsBuddyApp', '0007_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('sports', models.CharField(choices=[('Tennis', 'Tennis'), ('Cricket', 'Cricket'), ('Baseball', 'Baseball'), ('Football', 'Football')], max_length=50)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('twitter', models.CharField(max_length=40, null=True)),
                ('snap', models.CharField(max_length=40, null=True)),
                ('bio', models.TextField(default='Please Enter bio')),
                ('created_events', models.ManyToManyField(blank=True, related_name='created_events', to='SportsBuddyApp.Event')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('joined_events', models.ManyToManyField(blank=True, related_name='joined_events', to='SportsBuddyApp.Event')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
