# Generated by Django 3.1.3 on 2021-07-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0002_auto_20210625_1541'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('None', 'None'), ('Friend Request Recieved', 'Frnd Rqst Recieved'), ('Join Request Recieved', 'Join Rqst Recieved'), ('Friend Request Accepted', 'Frnd Rqst Accepted'), ('Join Request Accepted', 'Join Rqst Accepted')], default='None')),
                ('frndRqst', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_frnd_rqst', to='friends.friendsrequest')),
                ('joinRqst', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_join_rqst', to='friends.friendsrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
