# Generated by Django 3.1.3 on 2021-07-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210705_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.TextField(choices=[('None', 'None'), ('Friend Request Recieved', 'Frnd Rqst Recieved'), ('Join Request Recieved', 'Join Rqst Recieved'), ('Friend Request Accepted', 'Frnd Rqst Accepted'), ('Join Request Accepted', 'Join Rqst Accepted')], default='None'),
        ),
    ]
