# Generated by Django 3.1.3 on 2021-07-05 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20210625_1541'),
        ('joinRequests', '0001_initial'),
        ('notifications', '0003_auto_20210705_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='frndRqst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_frnd_rqst', to='friends.friendsrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='joinRqst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_join_rqst', to='joinRequests.joinrequest'),
        ),
    ]
